image: java:8-jdk

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - chmod +x ./gradlew
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
  tags:
    - grad

test:
  stage: test
  variables:
    GIT_STRATEGY: clone
  script:
    -  chmod +x ./gradlew
    - ./gradlew check
  tags:
    - grad

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_REPO || true
    - git push -f heroku HEAD:master
  only:
    - develop
  tags:
    - grad


#image: gradle:alpine
#
#variables:
#  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
#  GIT_STRATEGY: clone
#
#before_script:
#  - chmod +x ./gradlew
#  - export GRADLE_USER_HOME='pwd'/.gradle
#
#build:
#  stage: build
#  tags:
#    - grad
#  script: ./gradlew --build-cache assemble
#  only:
#    refs:
#      - branches
#
#test:
#  stage: test
#  tags:
#    - grad
#  script: ./gradlew check
#  only:
#    refs:
#      - branches
#
#deploy-test:
#  stage: deploy
#  tags:
#    - dalfcs_gitlab_docker_ci
#  image: ruby:2.6
#  script:
#    - apt-get update -qy
#    - apt-get install -y ruby-dev
#    - gem install dpl
#    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
#  only:
#    - develop