image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_STRATEGY: clone


build:
  stage: build
  tags:
    - dalfcs_gitlab_docker_ci
  script: ./gradlew --build-cache assemble
  only:
    - loginsignupfunctionality
#    refs:
#      - branches

test:
  stage: test
  tags:
    - dalfcs_gitlab_docker_ci
  script: ./gradlew check
  only:
    - loginsignupfunctionality
#    refs:
#      -
#      - branches

deploy-test:
  stage: deploy
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:2.6
  script: 
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - loginsignupfunctionality