image: java:8-jdk

variables:
    GIT_STRATEGY: clone

stages:
 - build
 - test
 - deploy

before_script:
 - export GRADLE_USER_HOME=`pwd`/.gradle
 
 
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - loginsignupfunctionality
  tags:
    - grad

test:
  stage: test
  script:
    - chmod +x ./gradlew
    - ./gradlew check
  only:
    - loginsignupfunctionality
  tags:
    - grad
    
deploy:
    stage: deploy
    script:
      - git remote remove heroku
      - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_REPO || true
      - git remote -v
      - git push -fq heroku HEAD:master
    only:
      - loginsignupfunctionality
    tags:
    - grad
      
     